version: "3.9"

services:
  site:
    image: $WERF_WEB_BACKEND_DOCKER_IMAGE_NAME
    command: "/app/server"
    environment:
      WERF_LOG_VERBOSE: "on"
      LOG_LEVEL: "debug"
    volumes:
      - ".helm/multiwerf-dev.json:/app/multiwerf/multiwerf.json:ro"
  documentation-en:
    image: jekyll/jekyll:3
    working_dir: "/srv/jekyll-data/src/documentation"
    command: bash -c "
        mkdir -m 777 -p /srv/jekyll-data/_site/_en /srv/jekyll-data/src/documentation/.jekyll-cache &&
        jekyll serve --config _config.yml -d /srv/jekyll-data/_site/_en -P 4040 "
    volumes:
      - "../:/srv/jekyll-data/src/"
  documentation-ru:
    image: jekyll/jekyll:3
    working_dir: "/srv/jekyll-data/src/documentation"
    command: bash -c "
      mkdir -m 777 -p /srv/jekyll-data/_site/_ru /srv/jekyll-data/src/documentation/.jekyll-cache &&
      jekyll serve --config _config.yml,_config_ru.yml -d /srv/jekyll-data/_site/_ru  -P 4041 "
    volumes:
      - "../:/srv/jekyll-data/src/"
  front:
    image: nginx:latest
    volumes:
      - ".werf/nginx-dev.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
