AllCops:
  TargetRubyVersion: 2.1

Metrics/LineLength:
  Max: 130

Metrics/AbcSize:
  Max: 85

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 300

Style/DoubleNegation:
  Enabled: false

Style/FileName:
  Exclude:
    - 'spec/chef/testproject/recipes/**/*'

Style/SpaceInside:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Documentation:
  Enabled: false

EmptyMethod:
  Enabled: false
