redis:
  enabled: true
  host: 
    _default: example-2-stage-redis-master 
  port: 
    _default: 6379 
app:
  java_opt:
    _default: "--debug"
    production: ""
  url:
    _default: stage.example.com
    prodiction: example.com

mysql:
  host:
    _default: mysql
  exthost:
    production: mysql-somewhereelse.example.com
  extport:
    production: 3306
  db:
    _default: db_example
  user:
    _default: springuser
