---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/01-cm.yaml") . | sha256sum }}
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: frontend
{{ tuple "frontend" . | include "werf_container_image" | indent 8 }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: env-js
          mountPath: /app/dist/env.js
          subPath: env.js
{{ tuple "frontend" . | include "werf_container_env" | indent 8 }}
      - name: backend
{{ tuple "hello" . | include "werf_container_image" | indent 8 }}
        command:
        - java
        - -jar
        - /app/demo-1.0.jar $JAVA_OPT
        workingDir: /app
        ports:
        - name: http-back
          containerPort: 8080
          protocol: TCP
        env:
{{ tuple "hello" . | include "werf_container_env" | indent 8 }}
        - name: JAVA_OPT
          value: {{ pluck .Values.global.env .Values.app.java_opt | first | default .Values.app.java_opt._default | quote }}
        - name: S3ENDPOINT
          value: {{ pluck .Values.global.env .Values.app.s3.epurl | first | default .Values.app.s3.epurl._default | quote }}
        - name: S3KEY
          value: {{ pluck .Values.global.env .Values.app.s3.key | first | default .Values.app.s3.key._default | quote }}
        - name: S3SECRET
          value: {{ pluck .Values.global.env .Values.app.s3.secret | first | default .Values.app.s3.secret._default | quote }}
        - name: S3BUCKET
          value: {{ pluck .Values.global.env .Values.app.s3.bucket | first | default .Values.app.s3.bucket._default | quote }}
      volumes:
      - name: nginx-config
        configMap:
          name: {{ .Chart.Name }}-configmap
      - name: env-js
        configMap:
          name: {{ .Chart.Name }}-configmap
