# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
  en:
    f:
      - title: Back to documentation
        url: /documentation/index.html

  ru:
    f:
      - title: Назад к документации
        type: secondary
        url: /documentation/index.html

      - title: К выбору языка и CI-системы
        type: secondary
        url: /documentation/guides/applications-guide/

      - title: Как использовать гайд
        url: 000-task.html

      - title: Подготовка к работе
        url: 010-preparing.html

      - title: Базовые настройки
        url: "020-basic.html"
        sf:
          - title: Сборка
            url: "020-basic.html#building"
          - title: Конфигурирование инфраструктуры в виде кода
            url: "020-basic.html#config-iac"
          - title: Построение CI-процесса
            url: "020-basic.html#ci"

      - title: Подключаем зависимости
        url: 030-dependencies.html

      - title: Генерируем и раздаём ассеты
        url: 040-assets.html

      - title: Работа с файлами
        url: 050-files.html

      - title: Работа с электронной почтой
        url: 060-email.html

      - title: Подключаем Redis
        url: 070-redis.html

      - title: Подключаем базу данных
        url: "080-database.html"
        sf:
          - title: Конфигурирование БД в Kubernetes
            url: "080-database.html#kubeconfig"
          - title: Подключение приложения к БД
            url: "080-database.html#appconnect"
          - title: Выполнение миграций
            url: "080-database.html#migrations"

      - title: Юнит-тесты и Линтеры
        url: 090-unittesting.html

      - title: Несколько приложений в одном репозитории
        url: 110-multipleapps.html

      - title: Динамические окружения
        url: 120-dynamicenvs.html




