---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name | quote }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/01-cm.yaml") . | sha256sum }}
      labels:
        app: {{ .Chart.Name | quote }}
    spec:
      imagePullSecrets:
        - name: registrysecret
      initContainers:
      - name: wait-mysql
        image: alpine:3.9
        command:
        - /bin/sh
        - -c
        - while ! getent ahostsv4 $MYSQL_HOST; do echo waiting for mysql; sleep 2; done
        env:
        - name: MYSQL_HOST
          value: {{ pluck .Values.global.env .Values.mysql.host | first | default .Values.mysql.host._default }}
      containers:
      - name: frontend
{{ tuple "frontend" . | include "werf_container_image" | indent 8 }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: env-js
          mountPath: /app/dist/env.js
          subPath: env.js
{{ tuple "frontend" . | include "werf_container_env" | indent 8 }}
      - name: backend
{{ tuple "hello" . | include "werf_container_image" | indent 8 }}
        command:
        - java
        - -jar
        - /app/target/demo-1.0.jar $JAVA_OPT
        workingDir: /app
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: JAVA_OPT
          value: {{ pluck .Values.global.env .Values.app.java_opt | first | default .Values.app.java_opt._default }}
        - name: REDISHOST
          value: {{ pluck .Values.global.env .Values.redis.host | first | default .Values.redis.host_default | quote }}
        - name: REDISPORT
          value: {{ pluck .Values.global.env .Values.redis.port | first | default .Values.redis.port_default | quote }}
        - name: MYSQL_HOST
          value: {{ pluck .Values.global.env .Values.mysql.host | first | default .Values.mysql.host._default }}
        - name: MYSQL_DATABASE
          value: {{ pluck .Values.global.env .Values.mysql.db | first | default .Values.mysql.db._default }}
        - name: MYSQL_PASSWORD
          value: {{ pluck .Values.global.env .Values.mysql.password | first | default .Values.mysql.password._default }}
        - name: MYSQL_USER
          value: {{ pluck .Values.global.env .Values.mysql.user | first | default .Values.mysql.user._default }}
{{ tuple "hello" . | include "werf_container_env" | indent 8 }}
      volumes:
      - name: nginx-config
        configMap:
          name: {{ .Chart.Name }}-configmap
      - name: env-js
        configMap:
          name: {{ .Chart.Name }}-configmap

