---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name | quote }}
spec:
  selector:
    app: {{ .Chart.Name | quote}}
  ports:
  - name: http-front
    port: 80
    targetPort: 80
  - name: http
    port: 8080
    targetPort: 8080
