redis:
  enabled: true

app:
  java_opt:
    _default: "--debug"
    production: ""
  url:
    _default: stage.example.com
    prodiction: example.com

redis:
  host:
    _default: example-2-stage-redis-master
  port:
    _default: 6379

mysql:
  host:
    _default: mysql
  db:
    _default: db_example
  user:
    _default: springuser
