---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-migrate-db
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ .Chart.Name }}-migrate-db
    spec:
      initContainers:
      - name: wait-postgres
        image: postgres:12
        command:
          - "sh"
          - "-c"
          - "until pg_isready -h {{ pluck .Values.global.env .Values.app.postgresql.host | first }} -U {{ .Values.app.postgresql.user }}; do sleep 2; done;"
      containers:
      - name: node
{{ tuple "node" . | include "werf_container_image" | indent 8 }}
        command: ["npm", "migrate"]
        env:
        - name: DATABASE_URL
          value: "postgresql://{{ .Values.app.postgresql.user }}:{{ pluck .Values.global.env .Values.app.postgresql.password | first }}@{{ pluck .Values.global.env .Values.app.postgresql.host | first }}:5432/{{ .Values.app.postgresql.db }}"
{{ tuple "node" . | include "werf_container_env" | indent 10 }}
      restartPolicy: Never