---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name | quote }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ pluck .Values.global.env .Values.app.url | first | default .Values.app.url._default }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name | quote }}
          servicePort: 8080
